# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Deploy to Expo App
      env:
        USERNAME: ${{secrets.EXPO_CLI_USERNAME}}
        PASSWORD: ${{secrets.EXPO_CLI_PASSWORD}}
        SENTRY_ORG: ${{secrets.SENTRY_ORG}}
        SENTRY_PROJECT: ${{secrets.SENTRY_PROJECT}}
        SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
      run: |
        sudo yarn global add expo-cli
        expo login -u "$USERNAME" -p "$PASSWORD"
        yarn
        expo publish
